//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWSoftware.PDI.Windows.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PDIWinForms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDIWinForms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWSoftware.PDI.Windows.Forms.PDIWinForms", typeof(PDIWinForms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string APDaily {
            get {
                return ResourceManager.GetString("APDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        internal static string APHourly {
            get {
                return ResourceManager.GetString("APHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        internal static string APMinutely {
            get {
                return ResourceManager.GetString("APMinutely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string APMonthly {
            get {
                return ResourceManager.GetString("APMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        internal static string APSecondly {
            get {
                return ResourceManager.GetString("APSecondly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        internal static string APWeekly {
            get {
                return ResourceManager.GetString("APWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        internal static string APYearly {
            get {
                return ResourceManager.GetString("APYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string BCCountInd {
            get {
                return ResourceManager.GetString("BCCountInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid day for the selected month must be specified.
        /// </summary>
        internal static string EditHAEBadDayOfMonth {
            get {
                return ResourceManager.GetString("EditHAEBadDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be blank.
        /// </summary>
        internal static string EditHAEBlankDesc {
            get {
                return ResourceManager.GetString("EditHAEBlankDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a holiday first.
        /// </summary>
        internal static string EditHMSelectHoliday {
            get {
                return ResourceManager.GetString("EditHMSelectHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday instance must not be null.
        /// </summary>
        internal static string ExHAEHolidayIsNull {
            get {
                return ResourceManager.GetString("ExHAEHolidayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recurrence object cannot be null.
        /// </summary>
        internal static string ExRPRecurrenceIsNull {
            get {
                return ResourceManager.GetString("ExRPRecurrenceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Holidays.
        /// </summary>
        internal static string HMErrorLoading {
            get {
                return ResourceManager.GetString("HMErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Holidays.
        /// </summary>
        internal static string HMErrorSaving {
            get {
                return ResourceManager.GetString("HMErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string HMFileDlgFilter {
            get {
                return ResourceManager.GetString("HMFileDlgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load holidays:
        ///{0}.
        /// </summary>
        internal static string HMLoadError {
            get {
                return ResourceManager.GetString("HMLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Holidays From XML File.
        /// </summary>
        internal static string HMLoadTitle {
            get {
                return ResourceManager.GetString("HMLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save holidays:
        ///{0}.
        /// </summary>
        internal static string HMSaveError {
            get {
                return ResourceManager.GetString("HMSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Holidays To XML File.
        /// </summary>
        internal static string HMSaveTitle {
            get {
                return ResourceManager.GetString("HMSaveTitle", resourceCulture);
            }
        }
    }
}
